"use client";
import {FormEvent,useEffect,useMemo,useState} from 'react'; import {WorkspacePerson,createWorkspaceId,loadActiveWorkspaceId,loadPeople,loadWorkspaces,savePeople} from '@/lib/workspaces'; import {WorkspaceSwitcher} from './WorkspaceSwitcher';
export function TalentPanel(){
 const [workspaceId,setWorkspaceId]=useState(''),[people,setPeople]=useState<WorkspacePerson[]>([]),[department,setDepartment]=useState('All'),[search,setSearch]=useState(''),[show,setShow]=useState(false);
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[jobTitle,setJobTitle]=useState(''),[newDept,setNewDept]=useState('Engineering');
 useEffect(()=>{setWorkspaceId(loadActiveWorkspaceId());setPeople(loadPeople())},[]);
 const workspace=loadWorkspaces().find(w=>w.id===workspaceId); const departments=useMemo(()=>['All',...Array.from(new Set(people.filter(p=>p.workspaceId===workspaceId).map(p=>p.department)))],[people,workspaceId]);
 const visible=people.filter(p=>p.workspaceId===workspaceId&&p.status==='active'&&(department==='All'||p.department===department)&&(`${p.name} ${p.jobTitle} ${p.department}`.toLowerCase().includes(search.toLowerCase())));
 function add(e:FormEvent){e.preventDefault();const p:WorkspacePerson={id:createWorkspaceId('person'),workspaceId,name:name.trim(),email:email.trim(),department:newDept,jobTitle:jobTitle.trim(),location:'Not specified',status:'active',teamDnaStatus:'not-started',strengths:[]};const next=[...people,p];setPeople(next);savePeople(next);setShow(false);setName('');setEmail('');setJobTitle('')}
 function remove(id:string){const next=people.map(p=>p.id===id?{...p,status:'inactive' as const}:p);setPeople(next);savePeople(next)}
 return <main className="v9-page"><section className="v9-hero compact"><div className="container"><span className="eyebrow">Talent Directory</span><h1>Manage the Talent Atlas can consider.</h1><p>Talent profiles remain private to the active workspace and are used only where consent allows.</p></div></section><section className="v9-body"><div className="container"><div className="v9-toolbar"><WorkspaceSwitcher value={workspaceId} onChange={setWorkspaceId}/><label>Department<select value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select></label><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, role or department"/></label><button className="button" onClick={()=>setShow(v=>!v)}>+ Add Talent</button></div>{show&&<form className="v9-inline-form" onSubmit={add}><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input required value={jobTitle} onChange={e=>setJobTitle(e.target.value)} placeholder="Job title"/><input required value={newDept} onChange={e=>setNewDept(e.target.value)} placeholder="Department"/><button className="button">Save Talent</button></form>}<div className="v9-table-card"><div className="v9-heading"><div><span className="eyebrow">{workspace?.name||'Workspace'}</span><h2>{visible.length} available talent profiles</h2></div><span className="v9-secure">Private workspace</span></div><div className="v9-people-grid">{visible.map(p=><article className="v9-person" key={p.id}><span className="avatar">{p.name.charAt(0)}</span><div><h3>{p.name}</h3><p>{p.jobTitle}</p><small>{p.department} • {p.location}</small></div><span className={p.teamDnaStatus==='ready'?'v9-dna ready':'v9-dna'}>{p.teamDnaStatus==='ready'?'Team DNA ready':'DNA not started'}</span><div className="chips">{p.strengths.slice(0,3).map(s=><span className="chip" key={s}>{s}</span>)}</div><button className="v9-link-button" onClick={()=>remove(p.id)}>Remove from Talent Directory</button></article>)}</div></div></div></section></main>
}
