export type OpportunityContext="professional"|"hackathon"|"community"|"sports"|"education"|"business";
export type OpportunityStatus="draft"|"open"|"forming"|"closed";
export type Opportunity={id:string;workspaceId:string;ownerId:string;title:string;objective:string;context:OpportunityContext;location:string;workingMode:"remote"|"hybrid"|"onsite"|"flexible";places:number;skills:string[];status:OpportunityStatus;createdAt:string;organisation?:string};
export type OpportunityInterestStatus="interested"|"shortlisted"|"invited"|"accepted"|"declined";
export type OpportunityInterest={id:string;opportunityId:string;userId:string;displayName:string;email:string;createdAt:string;status:OpportunityInterestStatus};
export type TeamBlueprintRole={id:string;title:string;reason:string;capabilities:string[]};
export type TeamBlueprint={opportunityId:string;generatedAt:string;teamSize:number;roles:TeamBlueprintRole[];strengths:string[];gapsToValidate:string[];summary:string};

const OK="autoteams.opportunities.v1",IK="autoteams.opportunity-interest.v1",BK="autoteams.opportunity-blueprints.v1",TK="autoteams-v20-saved-teams";
function read<T>(k:string):T[]{if(typeof window==="undefined")return[];try{const r=localStorage.getItem(k);return r?JSON.parse(r) as T[]:[]}catch{return[]}}
function write<T>(k:string,v:T[]){if(typeof window!=="undefined")localStorage.setItem(k,JSON.stringify(v))}
export const loadOpportunities=()=>read<Opportunity>(OK);
export const saveOpportunities=(v:Opportunity[])=>write(OK,v);
export function createOpportunity(input:Omit<Opportunity,"id"|"createdAt">){const x:Opportunity={...input,id:`opp-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:new Date().toISOString()};saveOpportunities([x,...loadOpportunities()]);return x}
export function updateOpportunity(id:string,patch:Partial<Opportunity>){const all=loadOpportunities(),e=all.find(x=>x.id===id);if(!e)return null;const u={...e,...patch};saveOpportunities(all.map(x=>x.id===id?u:x));return u}
export const loadOpportunityInterest=()=>read<OpportunityInterest>(IK);
export const saveOpportunityInterest=(v:OpportunityInterest[])=>write(IK,v);
export function expressInterest(input:Omit<OpportunityInterest,"id"|"createdAt"|"status">){const all=loadOpportunityInterest();const d=all.find(x=>x.opportunityId===input.opportunityId&&x.userId===input.userId);if(d)return d;const x:OpportunityInterest={...input,id:`interest-${Date.now()}`,createdAt:new Date().toISOString(),status:"interested"};saveOpportunityInterest([x,...all]);return x}
export function updateInterestStatus(id:string,status:OpportunityInterestStatus){const all=loadOpportunityInterest(),e=all.find(x=>x.id===id);if(!e)return null;const u={...e,status};saveOpportunityInterest(all.map(x=>x.id===id?u:x));return u}
export const loadBlueprints=()=>read<TeamBlueprint>(BK);
function roleFor(skill:string){const s=skill.toLowerCase();if(s.includes("product"))return"Product Lead";if(s.includes("design")||s.includes("ux"))return"Design / Experience";if(s.includes("risk")||s.includes("govern"))return"Risk / Governance";if(s.includes("deliver")||s.includes("project"))return"Delivery Lead";if(s.includes("ai")||s.includes("data")||s.includes("engineer")||s.includes("tech"))return"Technical Specialist";return"Team Contributor"}
export function generateTeamBlueprint(o:Opportunity){const skills=o.skills.length?o.skills:["Leadership","Delivery","Collaboration"];const roles:TeamBlueprintRole[]=[];for(const s of skills)roles.push({id:`role-${roles.length+1}`,title:roleFor(s),reason:`Provides ${s} capability needed for this objective.`,capabilities:[s]});while(roles.length<o.places)roles.push({id:`role-${roles.length+1}`,title:"Team Contributor",reason:"Adds capacity and complementary capability around the objective.",capabilities:[skills[roles.length%skills.length]]});const b:TeamBlueprint={opportunityId:o.id,generatedAt:new Date().toISOString(),teamSize:o.places,roles:roles.slice(0,o.places),strengths:["Designed around the objective","Capabilities are explicit","Human selection remains final"],gapsToValidate:["Availability and commitment","Experience evidence","Working-style fit"],summary:`Atlas proposes a ${o.places}-person team for ${o.title} using the stated objective and capabilities.`};write(BK,[b,...loadBlueprints().filter(x=>x.opportunityId!==o.id)]);return b}
export const findBlueprint=(id:string)=>loadBlueprints().find(x=>x.opportunityId===id)||null;
export function formTeamFromOpportunity(o:Opportunity,selected:OpportunityInterest[]){const b=findBlueprint(o.id);const team={id:`team-${Date.now()}`,workspaceId:o.workspaceId,name:o.title,purpose:o.objective,personIds:selected.map(x=>x.userId),createdAt:new Date().toISOString(),confidence:Math.min(95,70+selected.length*4),opportunityId:o.id,source:"opportunity",recommendation:{source:"fallback",summary:b?.summary||`Team formed from ${o.title}.`,teamStrengths:b?.strengths||["Shared objective"],skillGaps:selected.length<o.places?[`${o.places-selected.length} place(s) remain unfilled`]:[],risks:b?.gapsToValidate||[]}};write(TK,[team,...read<any>(TK)]);updateOpportunity(o.id,{status:selected.length>=o.places?"forming":"open"});return team}
export function opportunityContextLabel(c:OpportunityContext){return({professional:"Professional",hackathon:"Hackathon",community:"Community",sports:"Sports",education:"Education",business:"Business"} as const)[c]}
